const GENERAL_STATUS_ACTIVE = 'active';
const GENERAL_STATUS_INACTIVE = 'inactive';

const GENERAL_STATUS = [GENERAL_STATUS_ACTIVE, GENERAL_STATUS_INACTIVE];

module.exports = {GENERAL_STATUS_ACTIVE, GENERAL_STATUS_INACTIVE, GENERAL_STATUS};
